apiVersion: "sparkoperator.k8s.io/v1beta2"
kind: SparkApplication
metadata:
  name: spark-scala-file-k8-app
  namespace: default
spec:
  type: Scala
  mode: cluster
  image: "gcr.io/spark-operator/spark:v3.0.0"
  imagePullPolicy: Never
  mainClass: com.AppK8Demo
  mainApplicationFile: "local:///opt/spark/work-dir/jar/spark-scala-k8-app-assembly-0.1.jar"
  sparkVersion: "3.0.0"
  restartPolicy:
    type: Always
  volumes:
    - name: "app-volume"
      hostPath:
        path: "/Users/sugupta/Desktop/codebase/personal/spark-scala-k8-app/target/scala-2.12"
        type: Directory
    - name: "file-volume"
      hostPath:
        path: "/Users/sugupta/Desktop/codebase/personal/spark-scala-k8-app/src/main/resources"
        type: Directory
  driver:
    cores: 1
    coreLimit: "1200m"
    memory: "512m"
    labels:
      version: 3.0.0
    serviceAccount: spark
    volumeMounts:
      - name: "app-volume"
        mountPath: "/opt/spark/work-dir/jar"
      - name: "file-volume"
        mountPath: "/opt/spark/work-dir/src/main/resources"
  executor:
    cores: 1
    instances: 1
    memory: "512m"
    labels:
      version: 3.0.0
    volumeMounts:
      - name: "app-volume"
        mountPath: "/opt/spark/work-dir/jar"
      - name: "file-volume"
        mountPath: "/opt/spark/work-dir/src/main/resources"